<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Worker-67618541-884b-47ac-86eb-301d70507ada</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IndieGames.Application" Version="0.1.25" />
    <PackageReference Include="IndieGames.Domain" Version="0.1.11" />
    <PackageReference Include="IndieGames.Infrastructure" Version="0.1.26" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.4" />
  </ItemGroup>
</Project>
